In [11]:
import numpy as np
arr=np.array([1,2,3])
arr1=np.array([4,5,6])
arr2=np.concatenate((arr,arr1),axis=0) 
#concatenating two arrays
print('concatenating with axis 0')
print(arr2)


concatenating with axis 0
[1 2 3 4 5 6]


In [55]:
import numpy as np
arr=np.array([[1,2,3],[1,2,3,]])
arr1=np.array([[4,5,6],[2,3,4]])
arr2=np.concatenate((arr,arr1),axis=1) 
#concatenating two arrays
print('concatenating with axis 1')
print(arr2)


concatenating of two arrays
[[1 2 3 4 5 6]
 [1 2 3 2 3 4]]


In [13]:
import numpy as np
arr=np.array([1,2,3])
arr1=np.array([4,5,6])
con=np.concatenate((arr,arr1)) 
#concatenating two arrays
print('concatenating of two arrays')
print(con)


concatenating of two arrays
[1 2 3 4 5 6]


In [19]:
import numpy as np
data=np.array([1,3],[-2,5])
data1=np.array([2,6],[4,10])
rev=np.arr([20,30,40])
print(data)
print(data1)
print(rev)
print("/n reverse of array")
print(rev.flip(rev))
print(rev)


TypeError: Field elements must be 2- or 3-tuples, got '-2'